### ISSUE TITLE
Encrypt dan Decrypt Masukkan ke Promise / Worker Thread

### ISSUE THREAD

**Issue by GulajavaMinistudio** [fauzan121002/encryptlab#6]
Proses enkripsi dan dekripsi mungkin perlu dimasukkan ke dalam bungkusan Promise, sehingga bisa dipanggil secara Async Await atau Promise Chaining. Lalu supaya tidak terjadi blocking main thread dari Node JS itu sendiri.

```
module.exports.encrypt = (data,bit,mode,enc_key,iv) => {
   return new Promise((resolve) => {
    const cipher = crypto.createCipheriv('aes-'+bit+'-'+mode, enc_key, iv);

    let encrypted = cipher.update(data, 'utf8', 'base64');
    encrypted += cipher.final('base64');
    resolve(encrypted);
});
}
```

Alternatif lain adalah menggunakan multi threading dengan Worker Thread API, dan proses encrypt decrypt yang berat dan memakan waktu tidak menghambat thread dan event loop dari Node JS. 
Contoh :
[https://nodejs.org/api/worker_threads.html](https://nodejs.org/api/worker_threads.html )

Saya sendiri ada contoh penggunaan Worker Thread yang dikombinasikan dengan Promise. 
[https://github.com/javascript-indonesias/ExpressSimpleBoilerPlate/tree/master/src/workers](https://github.com/javascript-indonesias/ExpressSimpleBoilerPlate/tree/master/src/workers)

Btw, thanks untuk sampelnya, berguna banget buat bahan belajar dan diimplementasi langsung. 

:thumbsup: :thumbsup: :thumbsup: :thumbsup: :thumbsup:

**Comment by fauzan121002** [comment]
Terima kasih! , saya sudah menerapkan async await di commit terbaru saya.
[Cek disini](https://github.com/fauzan121002/encryptlab/commit/208e4ec5184c6806b0fdb6ed45f61d5968a9e945)
