### ISSUE TITLE
Improving examples...

### ISSUE THREAD

**Issue by tracker1** [fauzan121002/encryptlab#7]
When creating a crypto key from a known value would use pbkdf2 @ 10000 or higher iterations for the encryption key from known key, MD5 is *NOT* sufficient.  

When an IV or salt, it should be unique to each encode.  Can be added to the encrypted output or stored separately... re-using the IV or an empty salt allows for a broader attack surface, especially if the encoded content is simlar, such as JSON encoded objects, etc.

**Comment by fauzan121002** [comment]
I see, i will implement it on few encryption which not unique.

**Comment by fauzan121002** [comment]
Report : I already change the md5 to pbkdf2 @ 10000.
